//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallREC_Scribe.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallREC_Scribe.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 通话录音转录 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音识别配置 的本地化字符串。
        /// </summary>
        internal static string ConfigureApi {
            get {
                return ResourceManager.GetString("ConfigureApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名格式化配置 的本地化字符串。
        /// </summary>
        internal static string ConfigureParsing {
            get {
                return ResourceManager.GetString("ConfigureParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中 的本地化字符串。
        /// </summary>
        internal static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件夹失败 的本地化字符串。
        /// </summary>
        internal static string FolderSelectionFailed {
            get {
                return ResourceManager.GetString("FolderSelectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string Header_Date {
            get {
                return ResourceManager.GetString("Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号 的本地化字符串。
        /// </summary>
        internal static string Header_PhoneNumber {
            get {
                return ResourceManager.GetString("Header_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转录预览 的本地化字符串。
        /// </summary>
        internal static string Header_TranscriptionPreview {
            get {
                return ResourceManager.GetString("Header_TranscriptionPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        internal static string InvertSelection {
            get {
                return ResourceManager.GetString("InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择一个文件 的本地化字符串。
        /// </summary>
        internal static string SelectAtLeastOneFile {
            get {
                return ResourceManager.GetString("SelectAtLeastOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件夹 的本地化字符串。
        /// </summary>
        internal static string SelectFolderPrompt {
            get {
                return ResourceManager.GetString("SelectFolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转译选中 的本地化字符串。
        /// </summary>
        internal static string TranscribeSelected {
            get {
                return ResourceManager.GetString("TranscribeSelected", resourceCulture);
            }
        }
    }
}
